-- Module M1: Beneficiary Database Schema
-- Run this in Supabase SQL Editor if using Supabase Cloud

CREATE TABLE IF NOT EXISTS public."Beneficiaries" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ration_card_no TEXT UNIQUE NOT NULL,
    family_head_name TEXT NOT NULL,
    aadhaar_last4 TEXT NOT NULL,
    card_type TEXT DEFAULT 'PHH', -- AAY (Antyodaya), PHH (Priority), NPHH (Non-Priority)
    assigned_shop_id TEXT NOT NULL,
    family_members_count INT DEFAULT 4,
    monthly_quota JSONB NOT NULL,    -- { "Rice": 20, "Sugar": 5, "Wheat": 10, "Toor Dal": 2, "Palm Oil": 2 }
    current_month_lifted JSONB NOT NULL DEFAULT '{"Rice": 0, "Sugar": 0, "Wheat": 0, "Toor Dal": 0, "Palm Oil": 0}'::jsonb,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_beneficiaries_card ON public."Beneficiaries" (ration_card_no);
CREATE INDEX IF NOT EXISTS idx_beneficiaries_shop ON public."Beneficiaries" (assigned_shop_id);
